import { Temporal } from '@js-temporal/polyfill'
import { describe, expect, it } from 'vitest'
import fixture from './__fixtures__/conformance.json'
import { RuleEvaluator } from './evaluator'
import { assignColorSlot, assignLanes, barHasEnded, keyEntries, lanesForColumns, monthBars } from './layout'
import { regexPortabilityProblem } from './regexPortability'
import { decodeSharedRule, encodeSharedRule, isReadOnly } from './sharedRule'
import { regexRisk } from './regexRisk'
import { buildStripes } from './stripes'
import type { CalEvent, EvaluatedEvent, MatchType, Rule } from './types'

/**
 * The phone is the reference. These inputs and expected outputs were generated by
 * ConformanceExportTest in the Android app (feature/contextual-events) and copied here with
 * `npm run fixtures`. If one fails, the laptop and phone disagree, and the fix goes wherever the
 * bug is, not in this file.
 */
const zone = fixture.zone

function toEvent(e: (typeof fixture.events)[number]): CalEvent {
  const base = { id: e.id, calendarId: e.calendar, title: e.title, color: e.color }
  if (e.allDay) {
    return { ...base, allDay: true, startDate: Temporal.PlainDate.from(e.start), endDate: Temporal.PlainDate.from(e.end) }
  }
  const instant = (local: string) => Temporal.PlainDateTime.from(local).toZonedDateTime(zone).toInstant()
  return { ...base, allDay: false, start: instant(e.start), end: instant(e.end) }
}

function toRule(r: (typeof fixture.rules)[number]): Rule {
  return {
    type: r.type as MatchType,
    pattern: r.pattern,
    calendarId: r.calendar ?? undefined,
    enabled: r.enabled,
    keyName: r.keyName ?? undefined,
    keyColor: r.keyColor ?? undefined,
  }
}

const events = fixture.events.map(toEvent)
const evaluator = new RuleEvaluator(fixture.rules.map(toRule))
const evaluated: EvaluatedEvent[] = events.map((event) => evaluator.evaluate(event))
const contexts = evaluated.filter((e) => e.contextual)

describe('conformance with the phone', () => {
  it('decides the same events are contextual, with the same key name and colour', () => {
    expect(
      evaluated.map((e) => ({ event: e.event.id, contextual: e.contextual, keyName: e.keyName ?? null, keyColor: e.keyColor ?? null })),
    ).toEqual(fixture.evaluated)
  })

  it.each(fixture.weeks)('slices the week of $firstDay into the same stripes, lanes and key', (week) => {
    const stripes = lanesForColumns(buildStripes(contexts, Temporal.PlainDate.from(week.firstDay), week.days, zone, fixture.fallbackColor))
    expect(
      stripes.map((s) => ({ day: s.dayIndex, start: s.startMinute, end: s.endMinute, color: s.color, title: s.title, event: s.eventId, lane: s.lane, laneCount: s.laneCount })),
    ).toEqual(week.stripes)
    expect(keyEntries(stripes).map((k) => ({ title: k.title, color: k.color, event: k.eventId }))).toEqual(week.key)
  })

  it('lays out the same month bars, and dims the same ones as past', () => {
    const month = fixture.month
    const bars = monthBars(buildStripes(contexts, Temporal.PlainDate.from(month.firstDay), month.days, zone, fixture.fallbackColor))
    expect(bars.map((b) => ({ row: b.row, start: b.start, end: b.end, lane: b.lane, color: b.color, title: b.title, event: b.eventId }))).toEqual(month.bars)
    expect(bars.map((b) => barHasEnded(b, 16, 720))).toEqual(month.endedAtNow)
  })

  it.each(fixture.lanes)('packs lanes the same way: %#', (set) => {
    const placements = assignLanes(set.intervals.map(([group, start, end]) => ({ group, start, end })))
    expect(placements.map((p) => [p.lane, p.laneCount])).toEqual(set.placements)
  })

  it.each(fixture.colorSlots)('hands out the same colour slots: %#', (sequence) => {
    let slots: Record<string, number> = {}
    const assigned = sequence.titles.map((title) => {
      const [slot, updated] = assignColorSlot(slots, title)
      slots = updated ?? slots
      return slot
    })
    expect(assigned).toEqual(sequence.slots)
  })

  it.each(fixture.regexRisk)('judges regex risk the same: $pattern', ({ pattern, risk }) => {
    expect(regexRisk(pattern)).toEqual(risk)
  })

  it.each(fixture.regexPortability)('agrees on whether $pattern is portable', ({ pattern, problem }) => {
    expect(regexPortabilityProblem(pattern)).toEqual(problem)
  })

  it.each(fixture.regexMatch.cases)('matches the regex $pattern against the same titles', ({ pattern, matches }) => {
    const single = new RuleEvaluator([{ type: 'title_regex', pattern, enabled: true }])
    const titles = fixture.regexMatch.titles
    expect(titles.map((title) => single.isContextual(titleOnly(title)))).toEqual(matches)
  })

  it.each(fixture.containsMatch.cases)('matches "$pattern" (title contains) against the same titles', ({ pattern, matches }) => {
    const single = new RuleEvaluator([{ type: 'title_contains', pattern, enabled: true }])
    expect(fixture.containsMatch.titles.map((title) => single.isContextual(titleOnly(title)))).toEqual(matches)
  })
})

describe('the shared rule format, read the same on both sides', () => {
  it.each(fixture.sharedRules)('$input', ({ input, decoded, reencoded }) => {
    const rule = decodeSharedRule(input)
    if (decoded === null) {
      expect(rule).toBeNull()
      return
    }
    expect(rule).not.toBeNull()
    expect({
      version: rule!.version, uuid: rule!.uuid, updated: rule!.updated, enabled: rule!.enabled,
      type: rule!.type, pattern: rule!.pattern, calendarId: rule!.calendar?.id ?? null, calendarName: rule!.calendar?.name ?? null,
      eventCalendarId: rule!.event?.calendarId ?? null, eventId: rule!.event?.eventId ?? null, eventTitle: rule!.event?.title ?? null,
      keyName: rule!.keyName ?? null, keyColor: rule!.keyColor ?? null, readOnly: isReadOnly(rule!), extra: Object.keys(rule!.extra).sort(),
    }).toEqual(decoded)
    // what each side writes back means the same (byte order of keys may differ)
    expect(JSON.parse(encodeSharedRule(rule!))).toEqual(JSON.parse(reencoded!))
  })
})

function titleOnly(title: string): CalEvent {
  const instant = Temporal.Instant.fromEpochMilliseconds(0)
  return { id: 'x', calendarId: 'c', title, color: 0, allDay: false, start: instant, end: instant }
}
